import React, { useState } from "react";
//import CryptoJS from "crypto-js";
import "./App.css";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import Button from "@mui/material/Button";
import IconButton from "@mui/material/IconButton";
import MenuIcon from "@mui/icons-material/Menu";
import { useNavigate } from "react-router-dom";
//import ButtonGroup from "@mui/material/ButtonGroup";
const Home = () => {
  const navigate = useNavigate();
  const [isHover, setIsHover] = useState(false);

  const handleMouseEnter = () => {
    setIsHover(true);
  };

  const handleMouseLeave = () => {
    setIsHover(false);
  };

  const handleClick = () => {
    navigate("/Registation"); // Navigate to '/otherpage'
  };
  const handleClickl = () => {
    navigate("/Login"); // Navigate to '/otherpage'
  };
  return (
    <div className="ap">
      <div>
        <Box sx={{ flexGrow: 1 }}>
          <div>
            <AppBar
              position="static"
              style={{
                backgroundColor: isHover
                  ? "rgba(159, 90, 253, 0.25)"
                  : "rgba(159, 90, 253, 0)",
              }}
              sx={{
                position: "absolute",
                zindex: 1,
                borderRadius: 5,

                top: 0,
              }}
              onMouseEnter={handleMouseEnter}
              onMouseLeave={handleMouseLeave}
            >
              <Toolbar>
                <IconButton
                  size="large"
                  edge="start"
                  color="inherit"
                  aria-label="menu"
                  sx={{ mr: 2 }}
                >
                  <MenuIcon />
                </IconButton>
                <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
                  <h className="bodyhead">Hand gesture recognition </h>
                </Typography>

                <Button color="inherit" variant="outlined">
                  <h className="bodyhead" onClick={handleClickl}>
                    Login
                  </h>
                </Button>
                <div style={{ marginLeft: 10 }}></div>
                <div className="vl"></div>
                <div style={{ marginLeft: 10 }}></div>
                <Button
                  color="inherit"
                  variant="outlined"
                  onClick={handleClick}
                >
                  <h className="bodyhead">Register</h>
                </Button>
              </Toolbar>
            </AppBar>
          </div>
        </Box>
      </div>
      <br></br>
      <br></br>
      <br></br>
      <div class="container-fluid">
        <div class="row">
          <div class="col-sm-5" style={{ marginLeft: 100 }}>
            <Box
              sx={{
                height: 550,
                //  margin: 4.5,
                //  marginLeft: 2,
                borderRadius: 5,
                border: "red",
                backgroundColor: "rgba(0,0,0,0.3)",
                opacity: 0.95,
                "&:hover": {
                  backgroundColor: "rgba(0, 0, 0,0.6)",
                  opacity: 0.99,
                  boxShadow: "2px 3px 10px #F4AAB9",
                },
              }}
            >
              <div class="col-sm-15 text-white" style={{ borderRadius: 10 }}>
                <br></br>
                <br></br>
                <center>
                  <h className="bodyhead">
                    Welcome to our platform dedicated to hand gesture
                    recognition powered by Machine Learning (ML) models
                    utilizing Surface Electromyography (SEMG) signals. this
                    website focuses on the calibration and training of sEMG data collected
                    from sEMG sensors to detect and interpret hand gestures
                    accurately. and have coustom commands to the gesturesN
                  </h>
                  <br></br><br></br>
                  <h className="bodyhead" >Understanding SEMG Signals:</h><br></br>
                  <h className="bodyhead">
                     SEMG signals are electrical
                    signals generated by the muscles during contractions and
                    movements. These signals are captured by EMG sensors placed
                    on the skin's surface, providing insights into muscle
                    activity and movement patterns. Leveraging SEMG data, our
                    system interprets these signals to identify and classify
                    specific hand gestures.
                  </h>
                </center>
              </div>
            </Box>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
